//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BankResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RequestGenerator.Resources.BankResources", typeof(BankResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ABankRequest&gt;
        ///	&lt;Name&gt;{Name}&lt;/Name&gt;
        ///	&lt;Surname&gt;{Surname}&lt;/Surname&gt;
        ///	&lt;CardNumber&gt;{CardNumber}&lt;/CardNumber&gt;
        ///	&lt;Expiry&gt;{Expiry}&lt;/Expiry&gt;
        ///	&lt;Cvv&gt;{Cvv}&lt;/Cvv&gt;
        ///	&lt;OrderId&gt;{OrderId}&lt;/OrderId&gt;
        ///	&lt;Type&gt;{Type}&lt;Type&gt;
        ///&lt;/ABankRequest&gt;.
        /// </summary>
        public static string AlternatifBankRequestTemplate {
            get {
                return ResourceManager.GetString("AlternatifBankRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined!.
        /// </summary>
        public static string DefaultBankRequestTemplate {
            get {
                return ResourceManager.GetString("DefaultBankRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LBReq OrderId=&quot;{OrderId}&quot; Type=&quot;{Type}&quot;&gt;
        ///	&lt;Name&gt;{Name}&lt;/Name&gt;
        ///	&lt;Surname&gt;{Surname}&lt;/Surname&gt;
        ///	&lt;CardInformation&gt;
        ///		&lt;CardNumber&gt;{CardNumber}&lt;/CardNumber&gt;
        ///		&lt;Expiry&gt;{Expiry}&lt;/Expiry&gt;
        ///		&lt;Cvv&gt;{Cvv}&lt;/Cvv&gt;
        ///	&lt;/CardInformation&gt; 
        ///&lt;/LBReq&gt;.
        /// </summary>
        public static string LightBankRequestTemplate {
            get {
                return ResourceManager.GetString("LightBankRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SoftBankRequest&gt;
        ///	&lt;Personal&gt;
        ///		&lt;Name&gt;{Name}&lt;/Name&gt;
        ///		&lt;Surname&gt;{Surname}&lt;/Surname&gt;
        ///	&lt;/Personal&gt;
        ///	&lt;CardInformation&gt;
        ///		&lt;CardNumber&gt;{CardNumber}&lt;/CardNumber&gt;
        ///		&lt;Expiry&gt;{Expiry}&lt;/Expiry&gt;
        ///		&lt;Cvv&gt;{Cvv}&lt;/Cvv&gt;
        ///	&lt;/CardInformation&gt;
        ///	&lt;OrderId&gt;{OrderId}&lt;/OrderId&gt;
        ///	&lt;Type&gt;{Type}&lt;Type&gt;
        ///&lt;/SoftBankRequest&gt;.
        /// </summary>
        public static string SoftBankRequestTemplate {
            get {
                return ResourceManager.GetString("SoftBankRequestTemplate", resourceCulture);
            }
        }
    }
}
